-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 15:50:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `studio` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NULL,
  `age_rating` VARCHAR(45) NULL,
  `runtime` TIME NULL,
  `date_entered` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `date_entered` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`showing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`showing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie` INT NULL,
  `room_number` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `date_entered` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `movie_idx` (`movie` ASC) VISIBLE,
  CONSTRAINT `showing_movie`
    FOREIGN KEY (`movie`)
    REFERENCES `mydb`.`movie` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer` INT NOT NULL,
  `movie` INT NULL,
  `show_id` INT NULL,
  `price` DOUBLE NOT NULL,
  `date_entered` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `movie_idx` (`movie` ASC) VISIBLE,
  INDEX `customer_idx` (`customer` ASC) VISIBLE,
  INDEX `show_id_idx` (`show_id` ASC) VISIBLE,
  CONSTRAINT `ticket_movie`
    FOREIGN KEY (`movie`)
    REFERENCES `mydb`.`movie` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `ticket_customer`
    FOREIGN KEY (`customer`)
    REFERENCES `mydb`.`customer` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `ticket_show_id`
    FOREIGN KEY (`show_id`)
    REFERENCES `mydb`.`showing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Testing 
DROP TABLE movie;
DROP TABLE customer;
DROP TABLE showing;
DROP TABLE ticket;